package joukkue.test;
// Generated by ComTest BEGIN
import java.util.*;
import static org.junit.Assert.*;
import org.junit.*;
import joukkue.*;
// Generated by ComTest END

/**
 * Test class made by ComTest
 * @version 2021.03.24 09:14:14 // Generated by ComTest
 *
 */
@SuppressWarnings({ "all" })
public class JoukkueTest {



  // Generated by ComTest BEGIN
  /** testLisaa50 */
  @Test
  public void testLisaa50() {    // Joukkue: 50
    Pelaajat pelaajat = new Pelaajat(); 
    Pelaaja aku1 = new Pelaaja(), aku2 = new Pelaaja(); 
    assertEquals("From: Joukkue line: 53", 0, pelaajat.getLkm()); 
    pelaajat.lisaa(aku1); assertEquals("From: Joukkue line: 54", 1, pelaajat.getLkm()); 
    pelaajat.lisaa(aku2); assertEquals("From: Joukkue line: 55", 2, pelaajat.getLkm()); 
    pelaajat.lisaa(aku1); assertEquals("From: Joukkue line: 56", 3, pelaajat.getLkm()); 
    assertEquals("From: Joukkue line: 57", aku1, pelaajat.anna(0)); 
    assertEquals("From: Joukkue line: 58", aku2, pelaajat.anna(1)); 
    assertEquals("From: Joukkue line: 59", aku1, pelaajat.anna(2)); 
    assertEquals("From: Joukkue line: 60", false, pelaajat.anna(1) == aku1); 
    assertEquals("From: Joukkue line: 61", true, pelaajat.anna(1) == aku2); 
    try {
    assertEquals("From: Joukkue line: 62", aku1, pelaajat.anna(5)); 
    fail("Joukkue: 62 Did not throw IndexOutOfBoundsException");
    } catch(IndexOutOfBoundsException _e_){ _e_.getMessage(); }
    pelaajat.lisaa(aku1); assertEquals("From: Joukkue line: 63", 4, pelaajat.getLkm()); 
    pelaajat.lisaa(aku1); assertEquals("From: Joukkue line: 64", 5, pelaajat.getLkm()); 
    pelaajat.lisaa(aku1); assertEquals("From: Joukkue line: 65", 6, pelaajat.getLkm()); 
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** testAnnaPelipaikat102 */
  @Test
  public void testAnnaPelipaikat102() {    // Joukkue: 102
    Joukkue joukkue = new Joukkue(); 
    Pelaaja aku1 = new Pelaaja(), aku2 = new Pelaaja(), aku3 = new Pelaaja(); 
    aku1.rekisteroi(); aku2.rekisteroi(); aku3.rekisteroi(); 
    int id1 = aku1.getTunnusNro(); 
    int id2 = aku2.getTunnusNro(); 
    Pelipaikka puolustaja11 = new Pelipaikka(id1); joukkue.lisaa(puolustaja11); 
    Pelipaikka puolustaja12 = new Pelipaikka(id1); joukkue.lisaa(puolustaja12); 
    Pelipaikka puolustaja21 = new Pelipaikka(id2); joukkue.lisaa(puolustaja21); 
    Pelipaikka puolustaja22 = new Pelipaikka(id2); joukkue.lisaa(puolustaja22); 
    Pelipaikka puolustaja23 = new Pelipaikka(id2); joukkue.lisaa(puolustaja23); 
    List<Pelipaikka> loytyneet; 
    loytyneet = joukkue.annaPelipaikat(aku3); 
    assertEquals("From: Joukkue line: 118", 0, loytyneet.size()); 
    loytyneet = joukkue.annaPelipaikat(aku1); 
    assertEquals("From: Joukkue line: 120", 2, loytyneet.size()); 
    assertEquals("From: Joukkue line: 121", true, loytyneet.get(0) == puolustaja11); 
    assertEquals("From: Joukkue line: 122", true, loytyneet.get(1) == puolustaja12); 
    loytyneet = joukkue.annaPelipaikat(aku2); 
    assertEquals("From: Joukkue line: 124", 3, loytyneet.size()); 
    assertEquals("From: Joukkue line: 125", true, loytyneet.get(0) == puolustaja21); 
  } // Generated by ComTest END
}