package joukkue.test;
// Generated by ComTest BEGIN
import static org.junit.Assert.*;
import org.junit.*;
import joukkue.*;
// Generated by ComTest END

/**
 * Test class made by ComTest
 * @version 2021.03.24 09:07:16 // Generated by ComTest
 *
 */
@SuppressWarnings({ "all" })
public class PelaajatTest {



  // Generated by ComTest BEGIN
  /** testLisaa30 */
  @Test
  public void testLisaa30() {    // Pelaajat: 30
    Pelaajat pelaajat = new Pelaajat(); 
    Pelaaja aku1 = new Pelaaja(), aku2 = new Pelaaja(); 
    assertEquals("From: Pelaajat line: 33", 0, pelaajat.getLkm()); 
    pelaajat.lisaa(aku1); assertEquals("From: Pelaajat line: 34", 1, pelaajat.getLkm()); 
    pelaajat.lisaa(aku2); assertEquals("From: Pelaajat line: 35", 2, pelaajat.getLkm()); 
    pelaajat.lisaa(aku1); assertEquals("From: Pelaajat line: 36", 3, pelaajat.getLkm()); 
    assertEquals("From: Pelaajat line: 37", aku1, pelaajat.anna(0)); 
    assertEquals("From: Pelaajat line: 38", aku2, pelaajat.anna(1)); 
    assertEquals("From: Pelaajat line: 39", aku1, pelaajat.anna(2)); 
    assertEquals("From: Pelaajat line: 40", false, pelaajat.anna(1) == aku1); 
    assertEquals("From: Pelaajat line: 41", true, pelaajat.anna(1) == aku2); 
    try {
    assertEquals("From: Pelaajat line: 42", aku1, pelaajat.anna(5)); 
    fail("Pelaajat: 42 Did not throw IndexOutOfBoundsException");
    } catch(IndexOutOfBoundsException _e_){ _e_.getMessage(); }
    pelaajat.lisaa(aku1); assertEquals("From: Pelaajat line: 43", 4, pelaajat.getLkm()); 
    pelaajat.lisaa(aku1); assertEquals("From: Pelaajat line: 44", 5, pelaajat.getLkm()); 
    pelaajat.lisaa(aku1); assertEquals("From: Pelaajat line: 45", 6, pelaajat.getLkm()); 
  } // Generated by ComTest END
}