package joukkue.test;
// Generated by ComTest BEGIN
import java.util.*;
import static org.junit.Assert.*;
import org.junit.*;
import joukkue.*;
// Generated by ComTest END

/**
 * Test class made by ComTest
 * @version 2021.03.24 09:25:54 // Generated by ComTest
 *
 */
@SuppressWarnings({ "all" })
public class PelipaikatTest {



  // Generated by ComTest BEGIN
  /** testAnnaPelipaikat61 */
  @Test
  public void testAnnaPelipaikat61() {    // Pelipaikat: 61
    Pelipaikat pelipaikat = new Pelipaikat(); 
    Pelipaikka puolustaja21 = new Pelipaikka(2); pelipaikat.lisaa(puolustaja21); 
    Pelipaikka puolustaja11 = new Pelipaikka(1); pelipaikat.lisaa(puolustaja11); 
    Pelipaikka puolustaja22 = new Pelipaikka(2); pelipaikat.lisaa(puolustaja22); 
    Pelipaikka puolustaja12 = new Pelipaikka(1); pelipaikat.lisaa(puolustaja12); 
    Pelipaikka puolustaja23 = new Pelipaikka(2); pelipaikat.lisaa(puolustaja23); 
    Pelipaikka puolustaja51 = new Pelipaikka(5); pelipaikat.lisaa(puolustaja51); 
    List<Pelipaikka> loytyneet; 
    loytyneet = pelipaikat.annaPelipaikat(3); 
    assertEquals("From: Pelipaikat line: 74", 0, loytyneet.size()); 
    loytyneet = pelipaikat.annaPelipaikat(1); 
    assertEquals("From: Pelipaikat line: 76", 2, loytyneet.size()); 
    assertEquals("From: Pelipaikat line: 77", true, loytyneet.get(0) == puolustaja11); 
    assertEquals("From: Pelipaikat line: 78", true, loytyneet.get(1) == puolustaja12); 
    loytyneet = pelipaikat.annaPelipaikat(5); 
    assertEquals("From: Pelipaikat line: 80", 1, loytyneet.size()); 
    assertEquals("From: Pelipaikat line: 81", true, loytyneet.get(0) == puolustaja51); 
  } // Generated by ComTest END
}