package tietokanta.test;
// Generated by ComTest BEGIN
import static org.junit.Assert.*;
import org.junit.*;
import static tietokanta.HetuTarkistus.*;
// Generated by ComTest END

/**
 * Test class made by ComTest
 * @version 2021.03.24 09:27:35 // Generated by ComTest
 *
 */
@SuppressWarnings({ "all" })
public class HetuTarkistusTest {


  // Generated by ComTest BEGIN
  /** testHetunTarkistusMerkki21 */
  @Test
  public void testHetunTarkistusMerkki21() {    // HetuTarkistus: 21
    assertEquals("From: HetuTarkistus line: 22", 'N', hetunTarkistusMerkki("121212-222")); 
    assertEquals("From: HetuTarkistus line: 23", 'N', hetunTarkistusMerkki("121212-222S")); 
    assertEquals("From: HetuTarkistus line: 24", 'N', hetunTarkistusMerkki("121212-222N")); 
    assertEquals("From: HetuTarkistus line: 25", 'Y', hetunTarkistusMerkki("121212-231Y")); 
    assertEquals("From: HetuTarkistus line: 26", '7', hetunTarkistusMerkki("311212-2317")); 
    assertEquals("From: HetuTarkistus line: 27", '7', hetunTarkistusMerkki("311212-2317XY"));  // vaikka on liikaa merkkejä
    assertEquals("From: HetuTarkistus line: 28", 'F', hetunTarkistusMerkki("999999-9999XY"));  // vaikka on pvm väärin
    try {
    assertEquals("From: HetuTarkistus line: 29", 'N', hetunTarkistusMerkki("12121A-222S")); 
    fail("HetuTarkistus: 29 Did not throw NumberFormatException");
    } catch(NumberFormatException _e_){ _e_.getMessage(); }
    try {
    assertEquals("From: HetuTarkistus line: 30", 'N', hetunTarkistusMerkki("12121A-22")); 
    fail("HetuTarkistus: 30 Did not throw StringIndexOutOfBoundsException");
    } catch(StringIndexOutOfBoundsException _e_){ _e_.getMessage(); }
    try {
    assertEquals("From: HetuTarkistus line: 31", 'N', hetunTarkistusMerkki("121")); 
    fail("HetuTarkistus: 31 Did not throw StringIndexOutOfBoundsException");
    } catch(StringIndexOutOfBoundsException _e_){ _e_.getMessage(); }
  } // Generated by ComTest END
}